<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proyecto', 'doctrine');

/**
 * BaseProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idproyecto
 * @property string $proyecto
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdproyecto() Returns the current record's "idproyecto" value
 * @method string              getProyecto()   Returns the current record's "proyecto" value
 * @method Doctrine_Collection getUsuario()    Returns the current record's "Usuario" collection
 * @method Proyecto            setIdproyecto() Sets the current record's "idproyecto" value
 * @method Proyecto            setProyecto()   Sets the current record's "proyecto" value
 * @method Proyecto            setUsuario()    Sets the current record's "Usuario" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.proyecto');
        $this->hasColumn('idproyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('proyecto', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'idproyecto',
             'foreign' => 'idproyecto'));
    }
}