<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoEmpleado', 'doctrine');

/**
 * BaseTipoEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoempleado
 * @property string $empleado
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdtipoempleado() Returns the current record's "idtipoempleado" value
 * @method string              getEmpleado()       Returns the current record's "empleado" value
 * @method Doctrine_Collection getUsuario()        Returns the current record's "Usuario" collection
 * @method TipoEmpleado        setIdtipoempleado() Sets the current record's "idtipoempleado" value
 * @method TipoEmpleado        setEmpleado()       Sets the current record's "empleado" value
 * @method TipoEmpleado        setUsuario()        Sets the current record's "Usuario" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.tipoEmpleado');
        $this->hasColumn('idtipoempleado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('empleado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'idtipoempleado',
             'foreign' => 'idtipoempleado'));
    }
}