<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoUsuario', 'doctrine');

/**
 * BaseTipoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipousuario
 * @property string $tipousuario
 * @property Doctrine_Collection $UsuarioSistema
 * 
 * @method integer             getIdtipousuario()  Returns the current record's "idtipousuario" value
 * @method string              getTipousuario()    Returns the current record's "tipousuario" value
 * @method Doctrine_Collection getUsuarioSistema() Returns the current record's "UsuarioSistema" collection
 * @method TipoUsuario         setIdtipousuario()  Sets the current record's "idtipousuario" value
 * @method TipoUsuario         setTipousuario()    Sets the current record's "tipousuario" value
 * @method TipoUsuario         setUsuarioSistema() Sets the current record's "UsuarioSistema" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.TipoUsuario');
        $this->hasColumn('idtipousuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipousuario', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UsuarioSistema', array(
             'local' => 'idtipousuario',
             'foreign' => 'idtipousuario'));
    }
}