<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cargo', 'doctrine');

/**
 * BaseCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcargo
 * @property string $cargo
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdcargo() Returns the current record's "idcargo" value
 * @method string              getCargo()   Returns the current record's "cargo" value
 * @method Doctrine_Collection getUsuario() Returns the current record's "Usuario" collection
 * @method Cargo               setIdcargo() Sets the current record's "idcargo" value
 * @method Cargo               setCargo()   Sets the current record's "cargo" value
 * @method Cargo               setUsuario() Sets the current record's "Usuario" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.Cargo');
        $this->hasColumn('idcargo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cargo', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 70,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'idcargo',
             'foreign' => 'idcargo'));
    }
}