<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioSistema', 'doctrine');

/**
 * BaseUsuarioSistema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusuariosistema
 * @property integer $idtipousuario
 * @property integer $idusuario
 * @property string $psw
 * @property TipoUsuario $TipoUsuario
 * @property Usuario $Usuario
 * 
 * @method integer        getIdusuariosistema() Returns the current record's "idusuariosistema" value
 * @method integer        getIdtipousuario()    Returns the current record's "idtipousuario" value
 * @method integer        getIdusuario()        Returns the current record's "idusuario" value
 * @method string         getPsw()              Returns the current record's "psw" value
 * @method TipoUsuario    getTipoUsuario()      Returns the current record's "TipoUsuario" value
 * @method Usuario        getUsuario()          Returns the current record's "Usuario" value
 * @method UsuarioSistema setIdusuariosistema() Sets the current record's "idusuariosistema" value
 * @method UsuarioSistema setIdtipousuario()    Sets the current record's "idtipousuario" value
 * @method UsuarioSistema setIdusuario()        Sets the current record's "idusuario" value
 * @method UsuarioSistema setPsw()              Sets the current record's "psw" value
 * @method UsuarioSistema setTipoUsuario()      Sets the current record's "TipoUsuario" value
 * @method UsuarioSistema setUsuario()          Sets the current record's "Usuario" value
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioSistema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.UsuarioSistema');
        $this->hasColumn('idusuariosistema', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idtipousuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('psw', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoUsuario', array(
             'local' => 'idtipousuario',
             'foreign' => 'idtipousuario',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario',
             'onDelete' => 'CASCADE'));
    }
}