<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sede', 'doctrine');

/**
 * BaseSede
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idsede
 * @property string $sede
 * @property integer $activa
 * @property Doctrine_Collection $Configuracion
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdsede()        Returns the current record's "idsede" value
 * @method string              getSede()          Returns the current record's "sede" value
 * @method integer             getActiva()        Returns the current record's "activa" value
 * @method Doctrine_Collection getConfiguracion() Returns the current record's "Configuracion" collection
 * @method Doctrine_Collection getUsuario()       Returns the current record's "Usuario" collection
 * @method Sede                setIdsede()        Sets the current record's "idsede" value
 * @method Sede                setSede()          Sets the current record's "sede" value
 * @method Sede                setActiva()        Sets the current record's "activa" value
 * @method Sede                setConfiguracion() Sets the current record's "Configuracion" collection
 * @method Sede                setUsuario()       Sets the current record's "Usuario" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSede extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.Sede');
        $this->hasColumn('idsede', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sede', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('activa', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Configuracion', array(
             'local' => 'idsede',
             'foreign' => 'idsede'));

        $this->hasMany('Usuario', array(
             'local' => 'idsede',
             'foreign' => 'idsede'));
    }
}