<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Motivo', 'doctrine');

/**
 * BaseMotivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmotivo
 * @property string $motivo
 * @property boolean $activo
 * @property Doctrine_Collection $Movimiento
 * @property Doctrine_Collection $Permiso
 * 
 * @method integer             getIdmotivo()   Returns the current record's "idmotivo" value
 * @method string              getMotivo()     Returns the current record's "motivo" value
 * @method boolean             getActivo()     Returns the current record's "activo" value
 * @method Doctrine_Collection getMovimiento() Returns the current record's "Movimiento" collection
 * @method Doctrine_Collection getPermiso()    Returns the current record's "Permiso" collection
 * @method Motivo              setIdmotivo()   Sets the current record's "idmotivo" value
 * @method Motivo              setMotivo()     Sets the current record's "motivo" value
 * @method Motivo              setActivo()     Sets the current record's "activo" value
 * @method Motivo              setMovimiento() Sets the current record's "Movimiento" collection
 * @method Motivo              setPermiso()    Sets the current record's "Permiso" collection
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.Motivo');
        $this->hasColumn('idmotivo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('motivo', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Movimiento', array(
             'local' => 'idmotivo',
             'foreign' => 'idmotivo'));

        $this->hasMany('Permiso', array(
             'local' => 'idmotivo',
             'foreign' => 'idmotivo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}