<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Feriado', 'doctrine');

/**
 * BaseFeriado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idferiado
 * @property string $feriado
 * @property date $feriadofechdesde
 * @property date $feriadofechhasta
 * @property time $feriadohoradesde
 * @property time $feriadohorahasta
 * @property float $porcentajeferiado
 * @property float $porcentajenocturno
 * @property boolean $un_dia
 * @property boolean $tomar_anio
 * @property RelacionConfigFeriado $RelacionConfigFeriado
 * 
 * @method integer               getIdferiado()             Returns the current record's "idferiado" value
 * @method string                getFeriado()               Returns the current record's "feriado" value
 * @method date                  getFeriadofechdesde()      Returns the current record's "feriadofechdesde" value
 * @method date                  getFeriadofechhasta()      Returns the current record's "feriadofechhasta" value
 * @method time                  getFeriadohoradesde()      Returns the current record's "feriadohoradesde" value
 * @method time                  getFeriadohorahasta()      Returns the current record's "feriadohorahasta" value
 * @method float                 getPorcentajeferiado()     Returns the current record's "porcentajeferiado" value
 * @method float                 getPorcentajenocturno()    Returns the current record's "porcentajenocturno" value
 * @method boolean               getUnDia()                 Returns the current record's "un_dia" value
 * @method boolean               getTomarAnio()             Returns the current record's "tomar_anio" value
 * @method RelacionConfigFeriado getRelacionConfigFeriado() Returns the current record's "RelacionConfigFeriado" value
 * @method Feriado               setIdferiado()             Sets the current record's "idferiado" value
 * @method Feriado               setFeriado()               Sets the current record's "feriado" value
 * @method Feriado               setFeriadofechdesde()      Sets the current record's "feriadofechdesde" value
 * @method Feriado               setFeriadofechhasta()      Sets the current record's "feriadofechhasta" value
 * @method Feriado               setFeriadohoradesde()      Sets the current record's "feriadohoradesde" value
 * @method Feriado               setFeriadohorahasta()      Sets the current record's "feriadohorahasta" value
 * @method Feriado               setPorcentajeferiado()     Sets the current record's "porcentajeferiado" value
 * @method Feriado               setPorcentajenocturno()    Sets the current record's "porcentajenocturno" value
 * @method Feriado               setUnDia()                 Sets the current record's "un_dia" value
 * @method Feriado               setTomarAnio()             Sets the current record's "tomar_anio" value
 * @method Feriado               setRelacionConfigFeriado() Sets the current record's "RelacionConfigFeriado" value
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeriado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia.Feriado');
        $this->hasColumn('idferiado', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('feriado', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('feriadofechdesde', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('feriadofechhasta', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('feriadohoradesde', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('feriadohorahasta', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('porcentajeferiado', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('porcentajenocturno', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('un_dia', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('tomar_anio', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RelacionConfigFeriado', array(
             'local' => 'idferiado',
             'foreign' => 'idferiado',
             'onDelete' => 'CASCADE'));
    }
}