<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VDatosPersonales', 'sigefirrhh');

/**
 * BaseVDatosPersonales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cedula
 * @property string $primer_nombre
 * @property string $segundo_nombre
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $descripcion_cargo
 * @property string $estatus
 * @property string $telefono_oficina
 * @property string $telefono_celular
 * @property string $telefono_residencia
 * @property string $email
 * @property integer $codigo_nomina
 * @property string $dependencia
 * @property date $fecha_ingreso
 * @property string $nombre
 * @property string $periodicidad
 * @property string $unidad_administradora
 * @property date $fecha_nacimiento
 * @property string $sexo
 * @property string $estado_civil
 * @property integer $id_personal
 * @property integer $id_dependencia
 * @property integer $id_unidad_funcional
 * @property string $nombre_uf
 * @property integer $id_tipo_personal
 * 
 * @method integer          getCedula()                Returns the current record's "cedula" value
 * @method string           getPrimerNombre()          Returns the current record's "primer_nombre" value
 * @method string           getSegundoNombre()         Returns the current record's "segundo_nombre" value
 * @method string           getPrimerApellido()        Returns the current record's "primer_apellido" value
 * @method string           getSegundoApellido()       Returns the current record's "segundo_apellido" value
 * @method string           getDescripcionCargo()      Returns the current record's "descripcion_cargo" value
 * @method string           getEstatus()               Returns the current record's "estatus" value
 * @method string           getTelefonoOficina()       Returns the current record's "telefono_oficina" value
 * @method string           getTelefonoCelular()       Returns the current record's "telefono_celular" value
 * @method string           getTelefonoResidencia()    Returns the current record's "telefono_residencia" value
 * @method string           getEmail()                 Returns the current record's "email" value
 * @method integer          getCodigoNomina()          Returns the current record's "codigo_nomina" value
 * @method string           getDependencia()           Returns the current record's "dependencia" value
 * @method date             getFechaIngreso()          Returns the current record's "fecha_ingreso" value
 * @method string           getNombre()                Returns the current record's "nombre" value
 * @method string           getPeriodicidad()          Returns the current record's "periodicidad" value
 * @method string           getUnidadAdministradora()  Returns the current record's "unidad_administradora" value
 * @method date             getFechaNacimiento()       Returns the current record's "fecha_nacimiento" value
 * @method string           getSexo()                  Returns the current record's "sexo" value
 * @method string           getEstadoCivil()           Returns the current record's "estado_civil" value
 * @method integer          getIdPersonal()            Returns the current record's "id_personal" value
 * @method integer          getIdDependencia()         Returns the current record's "id_dependencia" value
 * @method integer          getIdUnidadFuncional()     Returns the current record's "id_unidad_funcional" value
 * @method string           getNombreUf()              Returns the current record's "nombre_uf" value
 * @method integer          getIdTipoPersonal()        Returns the current record's "id_tipo_personal" value
 * @method VDatosPersonales setCedula()                Sets the current record's "cedula" value
 * @method VDatosPersonales setPrimerNombre()          Sets the current record's "primer_nombre" value
 * @method VDatosPersonales setSegundoNombre()         Sets the current record's "segundo_nombre" value
 * @method VDatosPersonales setPrimerApellido()        Sets the current record's "primer_apellido" value
 * @method VDatosPersonales setSegundoApellido()       Sets the current record's "segundo_apellido" value
 * @method VDatosPersonales setDescripcionCargo()      Sets the current record's "descripcion_cargo" value
 * @method VDatosPersonales setEstatus()               Sets the current record's "estatus" value
 * @method VDatosPersonales setTelefonoOficina()       Sets the current record's "telefono_oficina" value
 * @method VDatosPersonales setTelefonoCelular()       Sets the current record's "telefono_celular" value
 * @method VDatosPersonales setTelefonoResidencia()    Sets the current record's "telefono_residencia" value
 * @method VDatosPersonales setEmail()                 Sets the current record's "email" value
 * @method VDatosPersonales setCodigoNomina()          Sets the current record's "codigo_nomina" value
 * @method VDatosPersonales setDependencia()           Sets the current record's "dependencia" value
 * @method VDatosPersonales setFechaIngreso()          Sets the current record's "fecha_ingreso" value
 * @method VDatosPersonales setNombre()                Sets the current record's "nombre" value
 * @method VDatosPersonales setPeriodicidad()          Sets the current record's "periodicidad" value
 * @method VDatosPersonales setUnidadAdministradora()  Sets the current record's "unidad_administradora" value
 * @method VDatosPersonales setFechaNacimiento()       Sets the current record's "fecha_nacimiento" value
 * @method VDatosPersonales setSexo()                  Sets the current record's "sexo" value
 * @method VDatosPersonales setEstadoCivil()           Sets the current record's "estado_civil" value
 * @method VDatosPersonales setIdPersonal()            Sets the current record's "id_personal" value
 * @method VDatosPersonales setIdDependencia()         Sets the current record's "id_dependencia" value
 * @method VDatosPersonales setIdUnidadFuncional()     Sets the current record's "id_unidad_funcional" value
 * @method VDatosPersonales setNombreUf()              Sets the current record's "nombre_uf" value
 * @method VDatosPersonales setIdTipoPersonal()        Sets the current record's "id_tipo_personal" value
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVDatosPersonales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('v_datos_personales');
        $this->hasColumn('cedula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('primer_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('segundo_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('primer_apellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('segundo_apellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('descripcion_cargo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estatus', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_oficina', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_celular', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_residencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_nomina', 'integer', 7, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dependencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_ingreso', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('periodicidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('unidad_administradora', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('sexo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado_civil', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_personal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_dependencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_unidad_funcional', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre_uf', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_tipo_personal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}