<?php

/**
 * PluginUsuarioSistemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUsuarioSistemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUsuarioSistemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUsuarioSistema');
    }
}