<?php

/**
 * PluginConfiguracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginConfiguracionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginConfiguracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginConfiguracion');
    }
}