<?php

/**
 * PluginCoordinadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCoordinadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCoordinadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCoordinador');
    }
}