<?php

/**
 * PluginProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProyecto');
    }
}