<?php

/**
 * PluginFeriadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFeriadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFeriadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFeriado');
    }
}