<?php

/**
 * PluginPermisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPermisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPermisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPermiso');
    }
}