<?php

/**
 * PluginTipoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTipoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTipoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTipoUsuario');
    }
}