<?php

/**
 * PluginTipoEmpleadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTipoEmpleadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTipoEmpleadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTipoEmpleado');
    }
}