<?php

/**
 * PluginSedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSede');
    }
}