<?php

/**
 * PluginMovimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMovimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMovimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMovimiento');
    }
}