<?php

/**
 * PluginDepartamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDepartamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDepartamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDepartamento');
    }
}