<?php

/**
 * PluginJefeUnidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJefeUnidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJefeUnidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJefeUnidad');
    }
}