<?php

/**
 * PluginCargoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCargoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCargoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCargo');
    }
}