<?php

/**
 * PluginUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUsuario');
    }
}