<?php

/**
 * PluginMotivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMotivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMotivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMotivo');
    }
}