all:
  stylesheets: 
    -  jquery/jquery-ui/jquery-ui-1.8.6.custom.css
#    -  jquery/jqTablas/tablas.css
  javascripts: 
    -  jquery/jquery-ui-1.8.6.custom.min.js
    -  jquery/jquery.ui.datepicker.js
    -  jquery/jquery.textareaCounter.plugin.js
    -  usuario/usuario.js
    
inicio_sesionSuccess:
 has_layout: false 
mensajesSuccess:
  has_layout: false
confirmar_claveSuccess:
  has_layout: false
confirmar_nominaSuccess:
  has_layout: false



indexSuccess:
  javascripts:    
    -  jquery/jquery.textareaCounter.plugin.js
