<?php

/**
 * CargoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CargoTable extends PluginCargoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CargoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cargo');
    }
    
    public function listarCargos($buscar=null){
        $q = Doctrine_Query::create()->from('Cargo c');
        if(!is_null($buscar) && $buscar){
                $buscar = explode(" ",$buscar);
                foreach($buscar as $palabra){
                        $q->orWhere("c.cargo LIKE '%".$palabra."%'");
                }
        }
        $q->orderBy("c.cargo ASC");
        return $q->execute();
        
    }

    public function listarCargosSelect(){
        $select = array();
        foreach($this->listarCargos() as $cargo):
            $select[$cargo->getIdCargo()]= $cargo->getCargo();
        endforeach;
        return $select;
    }
    
    public function buscarCargoJson($buscar=null){
            $datos = $this->listarCargos($buscar);
            $resultados = array();
            foreach($datos as $campo => $cargo):
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEditar\" onclick='editar_cargo(\"".$cargo->getIdcargo()."\",\"".$cargo->getcargo()."\")' >";
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEliminar\" onclick='eliminar_cargo(".$cargo->getIdcargo().")' >";
                    $resultados [$campo][2] =$cargo->getCargo();
            endforeach;
            return $resultados;

    } 
   
}