<?php

/**
 * ConfiguracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfiguracionTable extends PluginConfiguracionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfiguracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configuracion');
    }


	public function configuracion($idConfiguracion){  
		$q = Doctrine_Query::create()
		->from('Configuracion c')
		->andWhere("c.horaEntrada != ? ","00:00:00")
		->andWhere("c.horaSalida != ? ","00:00:00")
		->andWhere("c.idConfiguracion = ?",$idConfiguracion)
		->orderBy("c.idConfiguracion DESC")
		->fetchOne();
		return $q;
	}

        public function buscarConfiguracion($buscar=null,$campo="c.fecha",$ordenar="ASC"){
		$q = Doctrine_Query::create()
                        ->from('Configuracion c');
		if(!is_null($buscar) && $buscar){
			$buscar = explode(" ",$buscar);
			foreach($buscar as $palabra){
				$q->orWhere("c.fecha LIKE '%".$palabra."%'");
			}
		}
		$q->orderBy("$campo $ordenar");
		return $q->execute();
	}
        
        public function listarConfiguracionSelect(){
            $select = array();
            foreach($this->buscarConfiguracion() as $configuracion):
                $select[$configuracion->getIdConfiguracion()]= "Desde:".date("h:i a",(strtotime($configuracion->getHoraentrada())))." - Hasta:".date("h:i a",(strtotime($configuracion->getHorasalida())));
            endforeach;
            return $select;
        }
        
        public function buscarConfiguracionJson($data){
                $campo="";
                switch($data->getParameter("iSortCol_0")):
                     case "0":
                         $campo="c.horaentrada";
                     break;
                     case "1":
                         $campo="c.horasalida";
                     break;
                     case "2":
                         $campo="c.horamaxentrada";
                     break;
                     case "3":
                         $campo="c.precioticks";
                     break; 
                     case "4":
                         $campo="c.cestatique_x_jornada";
                     break;   
                endswitch;
                $datos = $this->buscarConfiguracion($data->getParameter("sSearch",false),$campo,$data->getParameter("sSortDir_0"));
		$resultados = array();
		foreach($datos as $campo => $configuracion):
			$js_configuracion = "\"".$configuracion->getIdconfiguracion()."\",".
                                            "\"".date("h:i a",(strtotime($configuracion->gethoraentrada())))."\"".",\"".date("h:i a",(strtotime($configuracion->getHorasalida())))."\",".
                                            "\"".($configuracion->getIdsede())."\","."\"".$configuracion->gethoramaxentrada()."\"".
                                            ",\"".$configuracion->getPrecioticks()."\","."\"".$configuracion->getCestatique_x_jornada()."\"".
                                            ",\"".date("h:i a",(strtotime($configuracion->getHoradesdedi())))."\"".",\"".date("h:i a",(strtotime($configuracion->getHorahastadi())))."\"".
                                            ",\"".date("h:i a",(strtotime($configuracion->getHoradesdeno())))."\"".",\"".date("h:i a",(strtotime($configuracion->getHorahastano())))."\"".
                                            ",\"".$configuracion->getPorcentajedi()."\"".",\"".$configuracion->getPorcentajeno()."\"";
			$resultados [$campo][] = "<div style='cursor:pointer' class='seleccion_campo' onclick='configuracion_seleccionar(".$js_configuracion.")'>".Asistencia::limitar_caracteres(date("h:i a",(strtotime($configuracion->gethoraentrada()))),15)."</div>";
			$resultados [$campo][] =Asistencia::limitar_caracteres(date("h:i a",(strtotime($configuracion->getHorasalida()))),15);
			$resultados [$campo][] =Asistencia::limitar_caracteres($configuracion->gethoramaxentrada()." min.",10);
			$resultados [$campo][] =Asistencia::limitar_caracteres($configuracion->getPrecioticks()." Bsf.",10);
			$resultados [$campo][] =Asistencia::limitar_caracteres($configuracion->getCestatique_x_jornada(),15).
                                                "<input type=\"hidden\" id=\"configuracion_id\" name=\"configuracion_id\" value=\"".$configuracion->getIdconfiguracion()."\" >";
		endforeach;
		return $resultados;
        }
        
}
