<?php

/**
 * DepartamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartamentoTable extends PluginDepartamentoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Departamento');
    }
    
    
     public function listarDepartamentos($buscar=null,$departamento=null){
		$q = Doctrine_Query::create()->from('Departamento d');
		if(!is_null($buscar) && $buscar){
			$buscar = explode(" ",$buscar);
			foreach($buscar as $palabra){
				$q->orWhere("d.departamento LIKE '%".$palabra."%'");
			}
                          if(!is_null($departamento) && $departamento && is_numeric($departamento)){
                     $q->andWhere("d.iddepartamento = ? ",$departamento);
                }
		}
		$q->orderBy("d.departamento ASC");
		return $q->execute();
     }
     
     public function listarDepartamentosSelect(){
         $select = array();
         foreach($this->listarDepartamentos() as $departamento):
             $select[$departamento->getIdDepartamento()]= $departamento->getDepartamento();
         endforeach;
         return $select;
     }
     
    static public function listaDepartamentosSelect(){
        $q = Doctrine_Query::create()
                ->from('Departamento d')
		->orderBy("d.departamento ASC")
                ->execute();
        $select = array();
        foreach($q as $campo):
            $select[$campo->getIddepartamento()] = $campo->getDepartamento();
        endforeach;
        return $select;
    }
    
    public function buscarDepartamentoJson($buscar=null){
            $datos = $this->listarDepartamentos($buscar);
            $resultados = array();
            foreach($datos as $campo => $departamento):
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEditar\" onclick='editar_departamento(\"".$departamento->getIddepartamento()."\",\"".$departamento->getdepartamento()."\")' >";
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEliminar\" onclick='eliminar_departamento(".$departamento->getIddepartamento().")' >";
                    $resultados [$campo][2] =Asistencia::limitar_caracteres($departamento->getdepartamento(),50);
            endforeach;
            return $resultados;
    }
    public function departamentoid($departamento=null){
        $q= Doctrine_Query::create()
                ->from('Departamento d');
                if(!is_null($departamento) && $departamento && is_numeric($departamento)){
                     $q->andWhere("d.iddepartamento = ? ",$departamento);
                }
                return $q->execute();
    }
    
    public function buscarDepartamentoPorCoordinador($usuario){
            $coordinadores = Doctrine_Core::getTable("Coordinador")->buscarCoordinadores($usuario);
            
            $resultado = array();
            foreach($coordinadores as $campo => $coordinador):
			$resultado[] =$coordinador->getDepartamentoId();
            endforeach;
            
            $q = Doctrine_Query::create()
                    ->select("d.iddepartamento, d.departamento")
                    ->from('Departamento d')
                    ->whereIn("d.iddepartamento",$resultado)
                    ->orderBy("d.departamento");

            return $q->execute();

            //print $q->getSqlQuery();
            //return $q->execute();
        }
    
}