<?php

/**
 * JefeUnidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JefeUnidadTable extends PluginJefeUnidadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JefeUnidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JefeUnidad');
    }
}