<?php

/**
 * MotivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MotivoTable extends PluginMotivoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MotivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Motivo');
    }


	public function listar($buscar=null,$campo="motivo",$ordenar="ASC"){
		$q = Doctrine_Query::create()
			->from('Motivo m')
			->andWhere("m.activo = ?",true);
                
                    if(!is_null($buscar) && $buscar){
                            $buscar = explode(" ",$buscar);
                            foreach($buscar as $palabra){
                                    $q->orWhere("m.motivo LIKE '%".$palabra."%'");
                            }
                    }
		$q->orderBy("motivo ASC");
		return $q->execute();
	}
        
        
        public function buscarMotivoJson($data){
                $campo="motivo";
                $datos = $this->listar($data->getParameter("sSearch",false),$campo,$data->getParameter("sSortDir_0"));
		$resultados = array();
		foreach($datos as $campo => $motivo):
			$js_motivo = "\"".$motivo->getIdmotivo()."\",".
                                            "\"".$motivo->getMotivo()."\"";
			$resultados [$campo][] = "<div style='cursor:pointer' class='seleccion_campo' onclick='motivo_seleccionar(".$js_motivo.")'>".Asistencia::limitar_caracteres($motivo->getMotivo(),70)."</div>".
                                                "<input type=\"hidden\" id=\"motivo_id\" name=\"motivo_id\" value=\"".$motivo->getIdmotivo()."\" >";
		endforeach;
		return $resultados;
        }
}
