<?php

/**
 * Movimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Movimiento extends PluginMovimiento{


	public function registro($mov,$estado,$registro,$Apellido_nombre,$calcular=false){
		$fecha = date('Y-m-d');
		if($calcular){
			$registro = Doctrine_Core::getTable('Movimiento')->movimientosUsuario($this->getIdusuario(),$fecha,"E")->fetchOne();
			print $registro->getFecha()."<br>";
                     //   $horas= (contarHoras($registro->getFecha(),$fecha)/60);
		}else{
			
		}
	}

	public function MovimientoPorUsuario($idUsuario){
 		return Doctrine_Core::create()
			->from("Movimiento m")
			->where("m.idUsuario = ? ", $idUsuario)
			->execute();
	}



}
