<?php

/**
 * Permiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Juan Casseus
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Permiso extends PluginPermiso{
    	public function save(Doctrine_Connection $conn = null){
		$this->setFecha(date("d-m-Y H:i:s"));
	return parent::save($conn);
	}
}
