<?php

/**
 * ProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoTable extends PluginProyectoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proyecto');
    }

        public function buscarProyectos($buscar=null){
		$q = Doctrine_Query::create()->from('Proyecto p');
		if(!is_null($buscar) && $buscar){
			$buscar = explode(" ",$buscar);
			foreach($buscar as $palabra){
				$q->orWhere("p.proyecto LIKE '%".$palabra."%'");
			}
		}
		$q->orderBy("p.proyecto ASC");
		return $q->execute();
        }
    
	public function buscarProyectoJson($buscar=null){
                $datos = $this->buscarProyectos($buscar);
		$resultados = array();
		foreach($datos as $campo => $proyecto):
                        $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEditar\" onclick='editar_proyecto(\"".$proyecto->getIdproyecto()."\",\"".$proyecto->getProyecto()."\")' >";
                        $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEliminar\" onclick='eliminar_proyecto(".$proyecto->getIdproyecto().")' >";
			$resultados [$campo][2] =$proyecto->getProyecto();
		endforeach;
		return $resultados;

	}
        
        public function listarProyectoSelect(){
            $select = array();
            foreach($this->buscarProyectos() as $proyecto):
                $select[$proyecto->getIdProyecto()] = $proyecto->getProyecto();
            endforeach;
            return $select;
        }
}
