<?php

/**
 * SedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SedeTable extends PluginSedeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sede');
    }

    public function listarSede($buscar=null){
		$q = Doctrine_Query::create()->from('Sede s');
		if(!is_null($buscar) && $buscar){
			$buscar = explode(" ",$buscar);
			foreach($buscar as $palabra){
				$q->orWhere("s.sede LIKE '%".$palabra."%'");
			}
		}
		$q->orderBy("s.sede ASC");
		return $q->execute();
    }
    
    public function listarSedeSelect(){
        $select = array();
        foreach($this->listarSede() as $sede):
            $select[$sede->getIdSede()] = $sede->getSede();
        endforeach;
        return $select;
    }
    
    public function buscarSedeJson($buscar=null){
            $datos = $this->listarSede($buscar);
            $resultados = array();
            foreach($datos as $campo => $sede):
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEditar\" onclick='editar_sede(\"".$sede->getIdsede()."\",\"".$sede->getSede()."\")' >";
                    $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEliminar\" onclick='eliminar_sede(".$sede->getIdsede().")' >";
                    $resultados [$campo][2] =Asistencia::limitar_caracteres($sede->getSede(),50);
            endforeach;
            return $resultados;

    }     
}