<?php

/**
 * TipoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoUsuarioTable extends PluginTipoUsuarioTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoUsuario');
    }
    
    public function buscarTipousuario($buscar=null){
        $q = Doctrine_Query::create()->from('TipoUsuario tu');
        if(!is_null($buscar) && $buscar){
                $buscar = explode(" ",$buscar);
                foreach($buscar as $palabra){
                        $q->orWhere("tu.tipousuario LIKE '%".$palabra."%'");
                }
        }
        $q->orderBy("tu.tipousuario ASC");
        return $q->execute();
    }
    
    public function listarTipoUsuarioSelect(){
            $select = array();
            foreach($this->buscarTipousuario() as $proyecto):
                $select[$proyecto->getIdtipousuario()] = $proyecto->getTipousuario();
            endforeach;
      return $select;
    }
}