<?php

/**
 * TipoEmpleadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoEmpleadoTable extends PluginTipoEmpleadoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoEmpleadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoEmpleado');
    }
    
    
     public function listarTipoEmpleado($buscar=null){
		$q = Doctrine_Query::create()->from('TipoEmpleado te');
		if(!is_null($buscar) && $buscar){
			$buscar = explode(" ",$buscar);
			foreach($buscar as $palabra){
				$q->orWhere("te.empleado LIKE '%".$palabra."%'");
			}
		}
		$q->orderBy("te.empleado ASC");
		return $q->execute();
        }
        
   public function listarTipoEmpleadoSelect(){
       $select = array();
       foreach($this->listarTipoEmpleado() as $tipoempleado):
           $select[$tipoempleado->getIdTipoempleado()]= $tipoempleado->getEmpleado();
       endforeach;
       return $select;
   } 
   
   public function buscarTipoEmpleadoJson($buscar=null){
                $datos = $this->listarTipoEmpleado($buscar);
		$resultados = array();
		foreach($datos as $campo => $empleado):
                        $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEditar\" onclick='editar_empleado(\"".$empleado->getIdtipoempleado()."\",\"".$empleado->getEmpleado()."\")' >";
                        $resultados [$campo][] = "<input type=\"button\" value=\"\" class=\"btnEliminar\" onclick='eliminar_empleado(".$empleado->getIdtipoempleado().")' >";
			$resultados [$campo][2] =$empleado->getEmpleado();
		endforeach;
		return $resultados;

	}
        
        public function listarEmpleado($id=null){
		$q = Doctrine_Query::create()->from('TipoEmpleado te');
		if(!is_null($id) && $id){
                    $q->orWhere("te.idtipoempleado =?",$id);
		}
		return $q->execute();
        }
   
}