<?php

/**
 * UsuarioSistemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioSistemaTable extends PluginUsuarioSistemaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioSistemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioSistema');
    }
    
    public function buscarUsuario($id_usuario){
        $ret = Doctrine_Query::create()
        ->from("UsuarioSistema c")
        ->where("c.idusuario = ?", $id_usuario)
        ->setHydrationMode(Doctrine::HYDRATE_RECORD);

        if ($ret->count() == 0) return null;
        else return $ret->execute()->getFirst();
    }

}