<?php

/**
 * UsuarioSistema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asistencia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UsuarioSistema extends PluginUsuarioSistema{

	public function save(Doctrine_Connection $conn = null){
		$this->setPsw(md5($this->getPsw()));
	return parent::save($conn);
	}
 
      /* public function __toString(){
          // return ($this->getPsw())?$this->getPsw():"123";
       }*/
}
